### ISSUE TITLE
Allow to read Release Notes while performing flash

### ISSUE THREAD

**Issue by Altair31** [flipperdevices/qFlipper#103]
It would be great if we are able to read the release note while upgrading our flipper.
For people like me who will update no matter what is in the patch, it would be interesting to use the update duration to read it.

**Comment by zhovner** [comment]
You can read it while updating via mobile app https://flpr.app/
![image](https://user-images.githubusercontent.com/774290/184647215-b541b175-e37e-4f10-9537-eb36b0135a35.png)

**Comment by Altair31** [comment]
Why are you talking about mobile app when I'm posting on desktop app tracker?
Mobile app is a real pain to provision firmware to the device (very slow due to BT speed rate) so I still use qFlipper desktop application.
Does the desktop app have the same hidden functionality?

**Comment by zhovner** [comment]
>Why are you talking about mobile app when I'm posting on desktop app tracker?

Because soon you will be enforced to use mobile app for additional features like NFC attacks and so on, so get used to it :)

>Does the desktop app have the same hidden functionality?

Yeah, you can press on release version and get the changelog
![image](https://user-images.githubusercontent.com/774290/184663485-fcf10e8c-1ea9-40c9-a26b-3193daf00083.png)
