### ISSUE TITLE
Broken Link to Bug Report Guide

### ISSUE THREAD

**Issue by MyGodItsFull0fStars** [flipperdevices/qFlipper#118]
In the README.md, the link (`https://github.com/flipperdevices/qFlipper/blob/dev/BUGS.md`) provided in the 'Reporting bugs' section is broken.

**Comment by gsurkov** [comment]
Changed the link to point to the bug report template.

**Comment by MyGodItsFull0fStars** [comment]
Thank you for the quick fix.
