### ISSUE TITLE
Repository Support

### ISSUE THREAD

**Issue by einfallstoll** [flipperdevices/qFlipper#130]
I like to have a bunch of repositories synced to my Flipper. So it would be cool to have an option to clone a repo directly to the filesystem and have qFlipper pulling it automatically when connected.

Bonus:
- This could be integrated to the mobile apps as well
- The Flipper could show a special repos folder in the file browser

**Comment by gsurkov** [comment]
There are no plans of implementing such a feature, as it would unnecessarily complicate qFlipper.
Please feel free to report any other bugs/feature requests.
