### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by hermanguilliman** [flipperdevices/qFlipper#137]
Can you add the drag and drop function for downloading files and directories from qFlipper?

**Comment by gsurkov** [comment]
This is planned, but not trivial to implement.

**Comment by KasoudraKZK** [comment]
there was the drag & drop function in a previous version... (1 month)
it was really useful, please put it back again

**Comment by gsurkov** [comment]
@KasoudraKZK if you are experiencing regressions with the new version, please create an issue and describe how to reproduce the said problem.
