### ISSUE TITLE
Drag and drop is disabled when running as admin

### ISSUE THREAD

**Issue by ase1590** [flipperdevices/qFlipper#138]
Windows 11 Build 22621

When Qflipper 1.2.1 is right clicked and Run as Administrator is chosen, the drag and drop functionality that is present during normal unprivileged runs is broken and files can no longer be dragged an dropped. 
The **right click -> upload files** option still works fine, just the ability to drag and drop is impacted. 

Not sure if this is intended behavior or a bug.

**Comment by kyhwana** [comment]
I think this is a windows UAC/Integrity Level thing. http://patrickablog.azurewebsites.net/index.php/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/

**Comment by gsurkov** [comment]
Unfortunately this is a built-in Windows behaviour and we can't change that. The "Run qFlipper" checkmark will be absent in the following versions to avoid confusion.
