### ISSUE TITLE
auto Update UI

### ISSUE THREAD

**Issue by gid9798** [flipperdevices/qFlipper#145]
**Describe the bug**
If the update fails, you will not be able to exit the application.

**To Reproduce**
Use the previous version of qFlipper
In my case 1.2.1
1. During the launch of qFlipper, agree to the update.
2. Wait for the download to finish
3. To the UAC request from Windows, answer "no"
4. You will see the message "update failed" and will not be able to exit it or continue working with the program until you restart it.

**Expected behavior**
An error window with a close button and the ability to continue working with the application.

**Actual behavior**
You can only close the application using alt+F4, taskbar or task manager

**Additional troubleshooting**
1. Does the issue persist if you try multiple times? - YES

**Additional context**
_Pressing the space bar on the error screen causes the update to download_
OS - Windows 11
qFlipper 1.2.1
Sorry for my English

**Comment by gsurkov** [comment]
Fixed in 432cf30750a3f1ef1ce3fae650e5fdc031d1bf78.
