### ISSUE TITLE
Some of the required modules (false) are not available.

### ISSUE THREAD

**Issue by stappersg** [flipperdevices/qFlipper#153]
Hi,

Screenshot:
```text
  ....
cd protobufinterface/ && make -f Makefile qmake_all
make[2]: Entering directory '/usr/src/github/flipperdevices/qFlipper/build/plugins/protobufinterface'
Some of the required modules (false) are not available.
Skipped.
  ....
```

It feels wrong that missing **required** are **skipped**.

Why are there no errors like #150 and #151 for missing `protobufinterface`?

**Comment by gsurkov** [comment]
This is just a hack to add a subproject without compilation units. Please disregard it.
