### ISSUE TITLE
qFlipper does not recognize an updated firmware bundle

### ISSUE THREAD

**Issue by hedger** [flipperdevices/qFlipper#156]
**Describe the bug**
qFlipper does not recognize an updated firmware bundle.

**To Reproduce**

 See https://github.com/flipperdevices/flipperzero-firmware/issues/1881

**Expected behavior**
An update package is uploaded and installed.

**Actual behavior**
Update package isn't installed. 

More info in the thread above. @[ankris812](https://github.com/ankris812)

**Comment by gsurkov** [comment]
Looks like a very minor bug on a special occasion, but it won't hurt to add CRC checks for all existing files to see whether they should be reuploaded or not.

**Comment by gsurkov** [comment]
Now qFlipper checks the md5 sums of the files on the SD card, if it finds any. It will also reupload any missing files.
