### ISSUE TITLE
Windows: Drag & Drop from ZIP Freeze

### ISSUE THREAD

**Issue by PirkCoyote** [flipperdevices/qFlipper#162]
Describe the bug
Attempting to upload a compatible file (txt, fmf, etc) by dragging and dropping out of a ZIP archive (via Windows 10 file explorer) and onto the Flipper file browser causes qFlipper to soft-hang with the "Please Wait / File Operation In Progress..." box animating. qFlipper apparently continues responding to events (no "Not Responding" indication appears in task manager) but cannot be interacted with other than moving the window. No actual file transfer appears to take place.

To Reproduce
1. Connect Flipper
2. Navigate to target folder within Flipper SD card
3. Open ZIP archive content view in Windows Explorer
4. Drag compatible file from Explorer ZIP file view onto qFlipper file explorer.

Expected behavior
File transfer success or file transfer attempt blocked/error message due to source file being inside an archive.

Actual behavior
qFlipper hangs and must be ended in Task Manager.

**Comment by gsurkov** [comment]
Now showing an error message if the user tries to drag a file from an archive manager.
