### ISSUE TITLE
Problems with screen dpi/Windows

### ISSUE THREAD

**Issue by eried** [flipperdevices/qFlipper#163]
**Describe the bug**
The window does not resize correctly if you move between different dpi in multimonitor setups

**To Reproduce**
1. Open qFlipper, move window to a screen with lower scale than another, i.e. 100%
![image](https://user-images.githubusercontent.com/1091420/218059593-870089c8-901b-4fb2-b598-4fb7bddb85ba.png)

2. Close and reopen qFlipper, so the window position is remembered on that screen
3. Move to higher scale screen, i.e. 150%
4. Contents of the window will be truncated (it resizes the content, but the window frame is too small):
![image](https://user-images.githubusercontent.com/1091420/218059535-0ddacab5-b6a6-41ae-96f4-bba48992db45.png)

**Expected behavior**
Normal window resize

**Actual behavior**
Wrong resize

**Additional context**
Running on Windows 10 22H2

**Comment by gsurkov** [comment]
@eried please try the development version to see if this was fixed.
The scaling behaviour was also changed (now qFlipper will switch to 2x scale at 175% system scale and not 150% as before).

**Comment by eried** [comment]
sure!

> development version

no dev releases with binaries? 🤔

**Comment by gsurkov** [comment]
> no dev releases with binaries?

[Here](https://update.flipperzero.one/builds/qFlipper/dev/), as usual!

**Comment by eried** [comment]
Works perfect on the same setup that the old version produced this dpi error, nice!
