### ISSUE TITLE
no more drag and drop?

### ISSUE THREAD

**Issue by KasoudraKZK** [flipperdevices/qFlipper#175]
**in an old version of Qflipper (dating from 1-2 months ago) it was possible to drag & drop files from windows to the SDcard via Qflipper, it was much more practical to move folders with subfolders without going through an adapter for the SDcard. this function has disappeared since the last 2 or 3 updates.**

I tried to reinstall, update but nothing works and 2 of my friends have the same issue which must be the same for everyone 

_*there's nothing at all in the logs that can be used for this problem*_

**Comment by gsurkov** [comment]
What operating system are you using?
Could you go through [the old versions](https://update.flipperzero.one/builds/qFlipper/) and find the last one which is working for you?

**Comment by KasoudraKZK** [comment]
I tried V 1.3.0 but it doesn't work I know it wasn't a drag and drop bug,
I don't know which version works, I'll test it later

I'm on Win10 pro 21H2

**Comment by gsurkov** [comment]
@KasoudraKZK are you running qFlipper with administrator privileges?
Windows automatically disables drag and drop for all applications that are run as administrator.

**Comment by KasoudraKZK** [comment]
yes indeed that was it...I did not know this rule..thank you

 for those who have the same problem check in the properties>compatibility of 
Qflipper that the box ''run this program as admin'' is disabled
