### ISSUE TITLE
After taking screenshot display stops updating

### ISSUE THREAD

**Issue by mumixam** [flipperdevices/qFlipper#180]
after taking a screenshot from qflipper the screen stops updating (via qFlipper).

using the binary image on Arch linux

sha1sum
4178c2edcce60ec6a1a5f27f1f503bc37359d0e6  qFlipper-x86_64-1.3.0.AppImage

**Comment by gsurkov** [comment]
Fixed in 5d2603c.

**Comment by mumixam** [comment]
Great. I've confirmed this works but this fix introduced another issue. Now the navigation on screen buttons do not work. When you press them you get the following error.

```[default] qrc:/components/StreamOverlay.qml:75: Error: Unknown method parameter type: InputEvent::Key```

EDIT: nevermind I see from another issue this is likely related to QT5. I'll try compiling against qt6

**Comment by gsurkov** [comment]
It was already reported in #178. 
In any case, please create a separate issue for each bug you are encountering. It's easy to overlook stuff in the comments.
