### ISSUE TITLE
Incorrect arrow controls in qFlipper in Universal Remotes

### ISSUE THREAD

**Issue by andbolt** [flipperdevices/qFlipper#187]
### Describe the bug.

Invalid response of arrow keys in qflipper while using the universal remotes. Up-Down arrows correspond to the horizontal movement, while Left-Right arrows correspond to the vertical movement (unlike the buttons on the Flipper itself).

### Reproduction

1. Open qFlipper with Flipper connected.
2. Enter Infrared -> Universal Remotes -> any of available options.
3. Check the response of navigation keys in qFlipper and on the Flipper itself.

### Anything else?

Firmware ver. 0.84.2.,qFlipper ver. 1.3.2.

**Comment by gsurkov** [comment]
The arrow keys worked okay, it's just the screen was not rotated correctly. Fixed in #202.
