### ISSUE TITLE
qFlipper's interface improvements proposal

### ISSUE THREAD

**Issue by RekordNadoev** [flipperdevices/qFlipper#188]
**Describe the bug**
Downloading and deleting several files from Flipper with qFlipper's filemanager looks like:
1) run qFlipper and open small non-resizeble filemanager with big icons
2) scroll to the file1
3) right-click -> Download -> Ok (filelist scrolls to top)
4) scroll to the file1
5) right-click -> Delete -> Delete
6) scroll to the file2
...

**To Reproduce**
Download and delete several files from Flipper with qFlipper's filemanager.

**Expected behavior**
1) run qFlipper, open filemanager.
2) resize window to fullscreen
3) see simple compact filelist
4) select range of files with "shift" or few files with "ctrl"
5) right click -> Download selected (maybe "Download and delete selected")
6) filelist position and selected files are the same
7) right click -> Delete selected

**Actual behavior**
Copied from description.
Downloading and deleting several files on Flipper with qFlipper's filemanager looks like:
1) run qFlipper and open small non-resizeble filemanager with big icons
2) scroll to the file1
3) right-click -> Download -> Ok (filelist scrolls to top)
4) scroll to the file1
5) right-click -> Delete -> Delete
6) scroll to the file2
...

**Additional troubleshooting**
1. Does the issue persist if you try multiple times?
- Yes

2. Does reconnecting/rebooting Flipper solve it?
- No

**Comment by gsurkov** [comment]
All major UI changes are planned for version 2.0. We'll probably be swithing things up a bit and the resizeable window as well as many other improvements are being discussed.
