### ISSUE TITLE
Provide Binarys download on Github Release page

### ISSUE THREAD

**Issue by lhpitn** [flipperdevices/qFlipper#195]
Hi,

for some reason the firewall in place here blocks all access to https://update.flipperzero.one/ ; so i was not able to download the software chosing this way, so it would be grate if you could also provide all the current downloads here on the github releases page ( https://github.com/flipperdevices/qFlipper/releases/tag/1.3.2 and so) 

thanks a lot in advance

**Comment by gsurkov** [comment]
Sorry, this is not planned. 
Ask your ISP to fix this issue, or if your area is subject to internet censorship, then there are ways to counteract that.
