### ISSUE TITLE
Renaming a file changing only letter case deletes the file

### ISSUE THREAD

**Issue by apoltix** [flipperdevices/qFlipper#198]
**Describe the bug**
In qFlipper's File manager, when renaming a file on the SD card changing only the filename's case (ABC -> abc), the file is deleted instead of renamed.

**To Reproduce**
1. In the qFlipper File manager, find a file on the SD card (I did not test on internal storage)
2. Rename the file changing only the filename's casing, e.g. from "ABC.txt" to "abc.txt"

The file now disappears and can no longer be found anywhere.

**Expected behavior**
The file is renamed correctly and continues to appear in the File manager.

**Actual behavior**
The file disappears from the File manager and is in fact deleted entirely.

**Additional troubleshooting**
This occurs in any folder I attempted a rename.

Renaming the file to something else beyond just a case-change, e.g. "ABC.txt" to "Abc 1.txt" to "Abc.txt" works fine.

**Additional context**
None

[qFlipper-20231014-142415.txt](https://github.com/flipperdevices/qFlipper/files/12905766/qFlipper-20231014-142415.txt)

**Comment by gsurkov** [comment]
This a firmware bug, not related to qFlipper.
The fix will be available in the next firmware release.
