### ISSUE TITLE
Problem with DFU 

### ISSUE THREAD

**Issue by theharlans** [flipperdevices/qFlipper#218]
Hi all-

Yet another issue.  I'm beginning to think I got a lemon.  Anyway, trying to reset the FZ and get it into DFU mode.  Hit "Repair" and then it seems to run but then ends with "Operation Error".  Logs attached.  Please help and thanks,

[qFlipper-20240420-121622.txt](https://github.com/flipperdevices/qFlipper/files/15049381/qFlipper-20240420-121622.txt)

**Comment by gsurkov** [comment]
Same underlying issue as in #217.
