### ISSUE TITLE
Windows installer doesn't create Start Menu shortcuts, neither Uninstall registry record

### ISSUE THREAD

**Issue by v0s** [flipperdevices/qFlipper#31]
Perhaps the qFlipper Windows installer should create:
1. Start Menu shortcuts, it's the default for installers on Windows
2. Uninstall record (displayed in Programs in Control Panel), it's the default way to uninstall software

**Comment by gsurkov** [comment]
Agreed, it would be a nice improvement.

**Comment by gsurkov** [comment]
Fixed in v0.7.8
