### ISSUE TITLE
qFlipper displays "Invalid Device", unable to update firmware

### ISSUE THREAD

**Issue by tlhunter** [flipperdevices/qFlipper#42]
I just received my flipper in the mail. It has a full charge and an older version of firmware, I think 0.43 or 0.40, something from December. I successfully scanned a few cards and IR remotes then discovered the internal storage was too low to scan more things. I inserted a 32GB micro SD card and formatted it using Flipper.

At this point I decided to update the firmware.

I'm using the Linux AppImage binary:

```sh
./qFlipper-x86_64-0.9.0.AppImage
```

The GUI runs but it is unable to connect to my device:

![2022-03-11_23-30-55](https://user-images.githubusercontent.com/551402/158008599-00e2f4f0-9026-49c4-ab75-6cf2e5a2d11e.png)

I'm using a laptop with no peripherals connected but the error persists.

Following [the docs](https://docs.flipperzero.one/8PvC5Nim38M7V0_khYFNp), I held down back and OK for thirty seconds until the device rebooted. The GUI still does not allow me to connect to the Flipper. `lsusb` confirms that the OS sees the device and that it is now in recovery mode:

```
Bus 006 Device 023: ID 0483:df11 STMicroelectronics STM Device in DFU Mode
```

Is there a better way to update the firmware? Perhaps writing a file to the sd card?

**Comment by tlhunter** [comment]
Here are some additional logs when plugging/unplugging the device from the computer with qFlipper running:

```
[APP] qFlipper version 0.9.0 commit 62c4653c 2022-03-04T08:08:03
[APP] OS info: Ubuntu 20.04.4 LTS 20.04 5.15.23-051523-generic
[DEBUG] Failed to open device
[DEVREG] Invalid device detected: VID_0x0:PID_0x0, ignoring it
[UPDATES] Fetched update information from https://update.flipperzero.one/qFlipper/directory.json
[UPDATES] Fetched update information from https://update.flipperzero.one/firmware/directory.json
[BACKEND] Finalized current operation
[DEBUG] Failed to open device
[DEVREG] Invalid device detected: VID_0x0:PID_0x0, ignoring it
```

Rebooting the device doesn't help. Switching cables doesn't help either.

**Comment by tlhunter** [comment]
I did the unthinkable and used my Windows desktop to install the firmware update. It worked without a hitch. I'll keep this thread open since there seems to be an issue with the AppImage build.

**Comment by zhovner** [comment]
Thanks. Your distro is `Ubuntu 20.04.4 LTS 20.04 5.15.23-051523-generic`?
What about user permissions to access TTY devices?

**Comment by gsurkov** [comment]
It does look like the device access rules have not been set up.
Please run [this script](https://github.com/flipperdevices/qFlipper/blob/dev/setup_rules.sh) and try again.

**Comment by zhovner** [comment]
@gsurkov what do you think about .deb repository and adding this script to install process? Maybe we can find someone who can maintain it.

**Comment by gsurkov** [comment]
@zhovner Ideally, we should have native packages for all popular linux distributions. And indeed, we need maintainers.

**Comment by benklop** [comment]
I just encountered this issue as well, on Manjaro. the linked script did the trick.

**Comment by gsurkov** [comment]
Made sure to display a message about access rules when this happens. Closing for now.

**Comment by tlhunter** [comment]
New message is very helpful. The linked script worked like a charm.

**Comment by acheong08** [comment]
> Please run [this script](https://github.com/flipperdevices/qFlipper/blob/dev/setup_rules.sh) and try again.

Fixed it!

**Comment by nekroun** [comment]
> It does look like the device access rules have not been set up. Please run [this script](https://github.com/flipperdevices/qFlipper/blob/dev/setup_rules.sh) and try again.

This was it for me, thank you so much!

**Comment by Martin-105** [comment]
It didn't help me, it gives me an error: zsh: event not found: /bin/sh

**Comment by Ocramius** [comment]
I had a similar problem on NixOS:

```console
❯ qFlipper-cli 
2 [CLI] Performing full firmware update...
2 [CLI] Waiting for devices...
411 [CLI] An error has occurred: BackendError::InvalidDevice. Exiting.
```

The provided BASH script didn't work: instead, I configured `udev` rules manually, using the latest version of the rules:

https://github.com/flipperdevices/qFlipper/blob/1d26683ff5b751f219a4e40443b7c8355eb39469/installer-assets/udev/42-flipperzero.rules (notice the added `GROUP="dialout"`)

```nix
{ config, lib, pkgs, ... }:
 
{
  services.udev.extraRules = ''
#Flipper Zero serial port
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5740", ATTRS{manufacturer}=="Flipper Devices Inc.", TAG+="uaccess", GROUP="dialout"
#Flipper Zero DFU
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", ATTRS{manufacturer}=="STMicroelectronics", TAG+="uaccess", GROUP="dialout"
#Flipper ESP32s2 BlackMagic
SUBSYSTEMS=="usb", ATTRS{idVendor}=="303a", ATTRS{idProduct}=="40??", ATTRS{manufacturer}=="Flipper Devices Inc.", TAG+="uaccess", GROUP="dialout"
#Flipper U2F
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5741", ATTRS{manufacturer}=="Flipper Devices Inc.", ENV{ID_SECURITY_TOKEN}="1"
  '';
}
```

Then

```sh
sudo nixos-rebuild test --flake .#my-system
sudo udevadm control --reload-rules
sudo udevadm trigger
```

After that, the flipper connected:

```console
❯ qFlipper-cli 
3 [CLI] Performing full firmware update...
3 [CLI] Waiting for devices...
87 [RPC] Starting RPC session...
198 [RPC] RPC session started successfully.
...
```
