### ISSUE TITLE
Remember installer choices for updates

### ISSUE THREAD

**Issue by alexwaibel** [flipperdevices/qFlipper#44]
During the qFlipper installation I've selected a different install path as well as opted out of the desktop icon. However, when I go to update flipper, the installer has forgotten these choices. It would be helpful to save these choices somewhere and use them as the defaults for the update installer.

**Comment by gsurkov** [comment]
Thanks for the suggestion! Will look into it later, when more critical issues will have been fixed (unless someone makes a PR implementing it).

**Comment by zhovner** [comment]
Fixed in this branch, please test https://update.flipperzero.one/builds/qFlipper/nsis_modern_ui/

**Comment by gsurkov** [comment]
Fix is now available in the [official release binary](https://flipperzero.one/update).
