### ISSUE TITLE
Installation / Update fails on latest release (installer 1.0.01) and installation is corrupted.

### ISSUE THREAD

**Issue by cboldon** [flipperdevices/qFlipper#54]
**Describe the bug**
Opening qFlipper prompted to update to the latest version of qFlipper (installer 1.0.1)

**To Reproduce**
1. Download qFlipper 1.0.1 installer
2. Run installer

**Expected behavior**
A successful installation

**Actual behavior**
Installer encounters a problem about 1/3 the way into install. Error message supplied:
"Error opening file for writing"
"[...]\images\arrow-down.png"
<img width="368" alt="flipper-screenshot" src="https://user-images.githubusercontent.com/634472/162536477-35ac3590-8a69-418f-aeee-a47faa54ece1.png">

**Additional troubleshooting**
1. If I click "Ignore" on the error dialog, another error message of similar type is displayed referencing another PNG file.

**Comment by zhovner** [comment]
Thanks for your report. 
Can you please tell:

1. What version of windows you are running?

2. Do you have admin permissions on your user account? 

3. Do you have UAC turned ON or OFF?

4. Did you see UAC warning "this file is running with admin permissions"?

Looks like you run installer without admin permissions or you have UAC turned off.

**Comment by zhovner** [comment]
Please try this version (choose EXE) https://update.flipperzero.one/builds/qFlipper/nsis_check_admin/

**Comment by zhovner** [comment]
Closed due to no response
