### ISSUE TITLE
Write local timestamp for each event

### ISSUE THREAD

**Issue by scottAnselmo** [flipperdevices/qFlipper#61]
Problem: Currently when doing things like firmware upgrades it is unclear when the last event happened. Neither the firmware update process for qFlipper nor the full log have a timestamp.

Solution: Write the local timestamp at the start of each new line/event

**Comment by gsurkov** [comment]
Should be relatively easy to implement, but what precision should it have?

**Comment by gsurkov** [comment]
Added timestamps in milliseconds from application start in console output and log files (but not in the application window). Available in 1.0.2.

**Comment by scottAnselmo** [comment]
Thanks for the quick turnaround, much appreciated!
