### ISSUE TITLE
Qt 6 support

### ISSUE THREAD

**Issue by JulyIghor** [flipperdevices/qFlipper#69]
Here is a patch for Qt 6 support. QML still need to be fixed.
Compiles on both Qt 5 and 6

[0001-Qt-6-support.patch.tar.gz](https://github.com/flipperdevices/qFlipper/files/8629752/0001-Qt-6-support.patch.tar.gz)

**Comment by zhovner** [comment]
>tgz

Can you please make a pull request instead?

**Comment by JulyIghor** [comment]
ok I'll do it later

**Comment by JulyIghor** [comment]
https://github.com/flipperdevices/qFlipper/pull/70
