### ISSUE TITLE
qFlipper requires Rosetta on macOS

### ISSUE THREAD

**Issue by nico** [flipperdevices/qFlipper#73]
1. Go to https://flipperzero.one/update on a mac with Apple Silicon (ie arm64)
2. Click on "Download qFlipper"
3. Try to start app

**Expected behavior**
Program runs.

**Actual behavior**
<img width="548" alt="Screen Shot 2022-05-16 at 6 39 04 PM" src="https://user-images.githubusercontent.com/3487/168693834-00cb05b8-8ccb-4862-aeba-5619aaf1728f.png">

**Comment by zhovner** [comment]
Some day we will move to Qt6 and make a separate builds for ARM macs, but right now this is the only way to use qFlipper.
