### ISSUE TITLE
[Feature Request] SD Card Folder Upload

### ISSUE THREAD

**Issue by GottZ** [flipperdevices/qFlipper#93]
Currently on qflipper 1.1.0 on Windows you can only upload Files to the device.
![image](https://user-images.githubusercontent.com/559564/181179362-eeca713f-babf-4e38-b711-d6e73b0de907.png)

This Issue requests the ability to upload folder structures as well.

related:
https://github.com/flipperdevices/qFlipper/blob/7a333ec99d5d853ad917787c2bb2b180b7b594ee/application/components/FileManager.qml#L255

**Comment by gsurkov** [comment]
Simply drag and drop a folder (or multiple folders) from Explorer to qFlipper's file manager.

**Comment by zhovner** [comment]
Can we close this issue?

**Comment by gsurkov** [comment]
Assuming the problem was solved. Please feel free to report further problems, if any.
