### ISSUE TITLE
[Feature request] Stolen Flippers check

### ISSUE THREAD

**Issue by LoZio** [flipperdevices/qFlipper#99]
Starting from this: https://forum.flipperzero.one/t/stolen-flipper-zero/5167

We should create a way to notify Flipper Devices of stolen Flippers, so that we can have a public register of stolen ones.
The qFlipper app should check upon connecting a device if it is in the list of stolen ones and warn the user.

**Comment by LoZio** [comment]
I didn't add the BUG label, have no idea how to remove it

**Comment by Astrrra** [comment]
I second this, sounds like a good idea.

**Comment by zhovner** [comment]
There is no way to prove that you own a flipper with specific serial number.
